
### **React App Data Tracking Sheet**

| **Component Name**        | **File Path** | **State Variables** | **Data Source** | **Data Destination** | **Props Sent** | **Props Received** | **Linked Components** | **Functions Called** | **Events Listened** | **Lifecycle Methods Used** | **Display Method** | **Status** | **Completion (%)** | **Notes** |
|---------------------------|---------------|---------------------|-----------------|----------------------|----------------|--------------------|-----------------------|----------------------|---------------------|----------------------------|--------------------|------------|--------------------|-----------|
| **BirthdayRewards**       |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **CustomerManagement**    |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **ExclusiveEvents**       |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **FavoriteShops**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **Favorites**             |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **Feedback**              |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **FlashSales**            |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **HelpAndSupport**        |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **HelpSupport**           |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **Index**                 |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **LastMinuteDeals**       |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **Leaderboard**           |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **NearbyOffers**          |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **Notifications**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **OfferDetail**           |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **OfferListing**          |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **OfferManagement**       |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **PartnerRewards**        |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **PointBoosters**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **PointDonation**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **PointTransfer**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **PointsHistory**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **Profile**               |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RedeemPoints**          |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RewardAndScanSystem**   |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RewardAuctions**        |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RewardBundles**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RewardCategories**      |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RewardCustomization**   |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RewardGiftingPage**     |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RewardRatings**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RewardSharing**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **RewardSubscription**    |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **ScanReceipt**           |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **Search**                |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **ShopAuthentication**    |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **ShopDashboard**         |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **ShopListing**           |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **ShopProfile**           |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **ShopRegistration**      |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **ShopSettings**          |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **SurpriseRewards**       |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **Wishlist**              |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |
| **WishlistSharing**       |               |                     |                 |                      |                |                    |                       |                      |                     |                            |                    | Not Done   | 0%                 |           |

